### PR TITLE
feat: add ci via github actions

### PR DESCRIPTION
**Pull request by Huskehhh**
Adds pylint via GitHub Actions.

TODO:
- [x] Finish warning cull
- [x] Create tickets to remove the need for pylint exclusions (done: https://trello.com/c/AiTh3Afg/18-remove-the-need-for-pylint-exclusions)
- [x] Ensure functionality didn't change (I think `about_page.py` background is cooked)
- [ ] Evaluate whether adding more to CI?
- [x] Maybe `.pylintrc` to ignore some more pedantic rules

### CODE REVIEW

**Comment by zinchenkoboris** [comment]
[Trello tutorial](https://trello.com/c/d8HX75dK/13-trello-tutorial)

**Comment by Huskehhh** [comment]
>  [Trello tutorial](https://trello.com/c/d8HX75dK/13-trello-tutorial)

Hey. This is the wrong PR to attach that ticket to.

**Comment by Huskehhh** [comment]
[Integrate GitHub Actions for CI/CD](https://trello.com/c/Irc9Eomk/9-integrate-github-actions-for-ci-cd)

**Comment by Huskehhh** [comment]
Ah, I've cooked this PR by adding work from the docs github action. I'll fix now.

**Comment by Huskehhh** [comment]
Fixed. :+1:

**Review by taysmith99 — APPROVED** [review]
Approved, looks great to me

**Pull request merged**
