### PR TITLE
feat: Cleanup repository and update documentation

### PR DESCRIPTION
**Pull request by Huskehhh**
Changes:
* Removes the multiple versions of the project
* Formats all files matching `*.py`
* Removes `AppDependencies.py` in favour of `requirements.txt`.
* Updated README to include simple instructions to get up and running.

If you wish to see the new structure, it is perhaps easier to view here: https://github.com/Huskehhh/PT-GUI

### CODE REVIEW

**Comment by Huskehhh** [comment]
[Improve GitHub Readme](https://trello.com/c/kaMMTaax/7-improve-github-readme)

**Comment by Huskehhh** [comment]
Need to verify if the testing network topology is to be included in the GitHub wiki pages or just as part of the internal project documentation.

**Comment by Huskehhh** [comment]
For future reference, here was the TODO list used.

TODO:
- [x] Validate no files are missed.
- [x] Test the README installation/setup instructions
- [x] Remove unused requirements from `requirements.txt`
- [x] What is the DevScripts folder?
- [x] Rename `EnummerationTools` to `EnumerationTools`
Per discussion with @taysmith99, this is unused.

**Comment by taysmith99** [comment]
> Need to verify if the testing network topology is to be included in the GitHub wiki pages or just as part of the internal project documentation.

Testing network topology is outdated and no longer needed, instead will include vulnerable software versions in the wiki pages.

**Comment by taysmith99** [comment]
Amazing work, documentation and cleanup of repo looks infinitely better, but testing fails to launch.

- AttackVector1.py line 103 & 104
- AttackVector8.py line 113 & 114

both have a character in them giving a syntax error.

A few tools are now missing the tkinter import (tk) and can't run.

**Review by taysmith99 — APPROVED** [review]
Tests run perfectly, approved

**Pull request merged**
